package com.gpetuhov.android.yellowstone;

import android.app.Application;

import com.gpetuhov.android.yellowstone.dagger.AppComponent;
import com.gpetuhov.android.yellowstone.dagger.AppModule;
import com.gpetuhov.android.yellowstone.dagger.DaggerAppComponent;

// Yellowstone application class.
// Builds and keeps instance of AppComponent,
// which is used to inject fields into application activities and fragments
public class YellowstoneApp extends Application {

    // Keeps instance of AppComponent
    private static AppComponent mAppComponent;

    @Override
    public void onCreate() {
        super.onCreate();

        // Build and keep AppComponent instance.
        // DaggerAppComponent is generated by Dagger.
        mAppComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this))
                .build();
    }

    public static AppComponent getAppComponent() {
        return mAppComponent;
    }
}
